apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.fullnameOverride }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.env }}
            env:
              {{- toYaml . | nindent 12 }}
            {{- end}}
            {{- if .Values.keyvault }}
            volumeMounts:
              {{- range $key, $value := .Values.keyvault.vaults }}
              - name: "{{ .Values.fullnameOverride }}-{{ $key | lower }}"
                mountPath: "/mnt/{{ $key }}-secrets-store"
                readOnly: true
              {{- end }}
            {{- end }}
          restartPolicy: OnFailure